const express = require("express");
const aboutGallery = require("../routes/aboutGallery");
const aboutGroup = require("../routes/aboutGroup");
const about = require("../routes/about");
const bg = require("../bg");
const homeGroup = require("../routes/homeGroup");
const home = require("../routes/home");
const divingGroup = require("../routes/divingGroup");
const divingGallery = require("../routes/divingGallery");
const diving = require("../routes/diving");
const event = require("../routes/event");
const privacy = require("../routes/privacy");
const resource = require("../routes/resource");
const users = require("../routes/users");
const auth = require("../routes/auth");
const error = require("../middleware/error");

module.exports = function (app) {
  app.use(express.json());
  app.use("/api/aboutGallery", aboutGallery);
  app.use("/api/aboutGroup", aboutGroup);
  app.use("/api/about", about);
  app.use("/api/bg", bg);
  app.use("/api/divingGallery", divingGallery);
  app.use("/api/divingGroup", divingGroup);
  app.use("/api/diving", diving);
  app.use("/api/homeGroup", homeGroup);
  app.use("/api/home", home);
  app.use("/api/event", event);
  app.use("/api/privacy", privacy);
  app.use("/api/resource", resource);
  app.use("/api/users", users);
  app.use("/api/auth", auth);
  app.use(error);
};
